# Generated by Django 2.2.3 on 2019-07-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='type',
            new_name='Type',
        ),
    ]
