# Generated by Django 2.2.3 on 2019-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20190727_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readers',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
