# Generated by Django 2.2.3 on 2019-07-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_blog_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
