# Generated by Django 2.2.3 on 2019-07-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_blog_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='null', upload_to='blogPics'),
            preserve_default=False,
        ),
    ]
