# Generated by Django 2.2.3 on 2019-07-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20190730_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), (None, 'Choose')], max_length=6),
        ),
    ]
