# Generated by Django 2.2.3 on 2019-08-02 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0007_auto_20190730_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Afghanistan', 'Afghanistan'), ('indonesia', 'indonesia'), (None, 'Click to choose')], max_length=11),
        ),
    ]
