# Generated by Django 2.2.3 on 2019-08-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20190802_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Afghanistan', 'Afghanistan'), ('Indonesia', 'Indonesia'), (None, 'Click to choose')], max_length=11),
        ),
    ]
