# Generated by Django 2.2.3 on 2019-08-03 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20190803_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
