# Generated by Django 2.2.3 on 2019-08-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_auto_20190803_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Afghanistan', 'Afghanistan'), ('Indonesia', 'Indonesia'), (None, 'Choose')], max_length=11),
        ),
    ]
